### ISSUE TITLE
Model navigation w/ Orion

### ISSUE THREAD

**Issue by NicolasAnquetil** [NicolasAnquetil/NewOrion#1]
Navigating Orion with long path.

Given the following diagram:
![orionNavigation](https://github.com/user-attachments/assets/f02d2f97-72db-4997-a6f8-c01a2b64afa2)

And the method to get the inheritance root:
```St
inheritanceRoot: aClass

	^aClass superclass
	ifNil: [ aClass ]
	ifNotNil: [ :superC | self inheritanceRoot: superC ]
```

It seems reasonable to think that  asking the `inheritanceRoot:` of `Class4(v2)` should return `Class1(v2)`

But it does not because Orion only looks at the version of the immediate sender of a query, and since Class2 and Class3 are not special in the version2 model, they think they belong to version1 model.

I created a test showing this https://github.com/NicolasAnquetil/Orion/blob/master/src/OrionTest/ORChainTest.class.st
(it only works with old FAMIX so old images)

The consequence is that one can not use Orion transparently and some complex queries for Famix will not run correctly with Orion.

It is not clear if we want to solve this. There does not seem to be any easy solution.

**Comment by anneetien** [comment]
According to me, it should be class1(v2). 
and should be possible to specify that you want the inheritanceRoot: class2 inVersion: v2.
For each navigation it should be possible to specify the version

**Comment by Ducasse** [comment]
In orion I think that we handle this else as soon as you have a navigation you end up not getting the right entity
so we should talk. I know that Andy Kellens optimise our version to support faster analysis. But the point is that there should be a lookup starting the version from which the query starts.

**Comment by NicolasAnquetil** [comment]
OK
I was wrong. There is a mechanism to propagate the version the query was initially on.
1. I did not `#versionIn:` sets the version for the entity it returns
2. In my test I used may be the only navigation method of FAMIXClass (`#superclass`) that does not support Orion.
    I should have used `superInheritances anyOne superclass`
